### ISSUE TITLE
Permettre de "roll" les objets/armes directement depuis l'inventaire

### ISSUE THREAD

**Issue by Lenullol** [Dilomos/aria_foundryvtt#40]
Actuellement, sauf erreur de ma part, on ne peut roll les dégâts des armes qu'uniquement depuis le panel "_**caractéristique**_". 

Hors si l'on dispose de plus de trois/quatre équipements rollable, l'ui sort un peu n'importe ou (ce qui est logique car c'est rare d'avoir plus de deux armes, mais il suffit d'avoir des bijoux conferant des sorts par exemple et cela devient complexe.)

Pour pallier à ce souci, cela pourrait être sympas dans le panel  "_**inventaire**_" de disposer du bouton de roll à côté du bouton "équiper" par exemple

**Comment by Dilomos** [comment]
Inclut dans la version 1.7.0
