### ISSUE TITLE
Supprimer les compétences d'une classe lorsqu'elle est déselectionnée

### ISSUE THREAD

**Issue by ravencr0w** [Dilomos/aria_foundryvtt#50]
Version testée : 1.8.0
Lorsque je sélectionne une classe (via drag & drop), les compétences spéciales associées sont bien ajoutées à la feuille de personnage.
En cliquant sur la croix à gauche de la classe, les compétences spéciales associées restent. On peut se retrouver avec plusieurs fois les mêmes compétences, voir cumuler les compétences entre classes.

**Comment by Dilomos** [comment]
En effet, ce choix était volontaire, je veux dire une fois une classe choisie on apprends les compétences associées mais si plus tard dans le jeu on change de classe, pourquoi devrait-on "oublier" notre ancien savoir ?
et même si c'est un peu fastidieux il reste la possibilité de supprimer ces compétences "en trop" manuellement une par une, si le joueur ou le MJ le souhaite.
Le fait d'ajouter les compétences automatiquement avec la classe est la pour rapidement recréer un personnage correspondant au pré-tiré du livre.

**Comment by Dilomos** [comment]
Mais qu'on soit bien clair je suis ouvert a la discussion, donc si tu as d'autres suggestion voir problème n’hésite pas les faire remonter ;)
Ce que je fait souvent c'est que je crée un personnage "poubelle" sur lequel je test les stat et/ou l'ajout de classe/compétences sans me soucier de ce qui pourrait rester de mes essai précédent, et quand je trouve une combinaison qui me plait ou qui plait a mes joueurs, la je crée la fiche "propre" de perso définitive

**Comment by ravencr0w** [comment]
Peut-être en amélioration pouvoir sélectionner plusieurs classes actives ? Un peu comme un multiclassage dans d'autres jeux de rôle ? Je vais regarder si je vois d'autres choses au fur et à mesure de mon utilisation :)

**Comment by Dilomos** [comment]
le multiclasse, pourquoi pas mais ça n'existe pas dans les règles ;)
Je le note quand même pour y regarder ;)
